[package]
name = "tgbot-app"
version = "0.1.1"
edition = "2021"
authors = ["HZzz2", "Leslie"]
# default-run = "tgbot-app"

[dependencies]
ferrisgram = "0.2.0"
serde_derive = "1.0"
serde_json = "1.0.117"
once_cell = "1.19.0"
reqwest = { version = "0.12.5", features = ["json","socks"] }
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
toml = "0.8.12"
rusty_ytdl = "0.7.1"
async-ssh2-tokio = "0.8.9"
async-channel = "2.3.1"
# anyhow = "1.0.86"
anyhow = { version = "1.0", default-features = false }
