### 使用前修改为自己的内容参数并将配置文件更名为：config.toml
### $cp config-template.toml config.toml
### 为了调用本地系统资源或程序，推荐使用系统服务的方式启动而不是docker启动

[telegram]
bot_token = "6763******fpaRuQ" #telegram bot token
bot_name = "N***Bot"           # telegram bot name
ids = ["6***9", "6***2"]       # telegram user id

[openai]
base_url = "https://api.openai.com/v1/chat/completions" # 请求地址 可更改
model = "gpt-3.5-turbo"                                 # 模型名,可更改"gpt-4"等受支持模型
api_key = "sk-kx****57c71"                              # API KEY

[command] # 定制常用的命令,使用方式：/c 1 ，输入不存在的key则显示所有已定制的命令,如/c 999
cmd = { "1" = "curl ipinfo.io", "2" = "df -h", "3" = "curl ip.fm", "4" = "curl wttr.in/Hunan", "唱" = "id", "跳" = "curl https://uapis.cn/api/say", "rap" = "curl https://uapis.cn/api/prohibited?text=鸡你太美", "查看所在目录" = "pwd" }

[brute_force]
ssh = { "username" = "root", "port" = "22", "brute_file" = "./ssh_password.txt", "threads" = "16", "display_message_time_interval_seconds" = "5" }


[yt_dlp] # 使用yt-dlp时是否使用代理
proxy = "" # 为空则不使用代理，默认不使用代理 (由于某些IP会被油管禁止，如果无法下载可以使用代理)
#proxy = "socks5://username:password@1.2.3.4:1080"  # 支持HTTP/HTTPS/SOCKS proxy 可选身份验证

[y_ytdl] # 目前reqwest好像不支持带身份验证socks5。HTTP/HTTPS可选择带身份验证，推荐
proxy = "" # 为空则不使用代理，默认不使用代理 (由于某些IP会被油管禁止，如果无法下载可以使用代理)
#proxy = "http://username:password@1.2.3.4:1880"  # HTTP/HTTPS可选身份验证，暂不支持带有账号密码验证的socks5。 reqwest crate本人测试后发现无法使用带身份验证的socks5代理 如果要使用，socks5要没有身份验证的才行，不推荐


# 以系统服务的方式运行此程序
# vim /etc/systemd/system/tgbot-app.service
# 添加一下内容
# [Unit]
# Description=电报机器人程序
# After=network.target

# [Service]
# ExecStart=/root/tgbot-app/tgbot-app
# WorkingDirectory=/root/tgbot-app
# Restart=always

# [Install]
# WantedBy=default.targe
