name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release - ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary-postfix: ""
            asset-name: linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary-postfix: ".exe"
            asset-name: windows-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            binary-postfix: ""
            asset-name: darwin-amd64
          - os: freebsd-latest
            target: x86_64-unknown-freebsd
            binary-postfix: ""
            asset-name: freebsd-amd64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Install OpenSSL on FreeBSD
        if: ${{ matrix.platform.os == 'freebsd-latest' }}
        run: |
          pkg install -y openssl

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Prepare Release Archive
        shell: bash
        run: |
          BINARY_NAME=$(grep -m1 '^name = ' Cargo.toml | cut -d '"' -f2)
          RELEASE_DIR="release"
          mkdir -p "$RELEASE_DIR"
          cp target/${{ matrix.platform.target }}/release/$BINARY_NAME${{ matrix.platform.binary-postfix }} "$RELEASE_DIR/"
          cp README.md LICENSE "$RELEASE_DIR/" 2>/dev/null || true
          
          cd "$RELEASE_DIR"
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a -tzip "../$BINARY_NAME-${{ matrix.platform.asset-name }}.zip" *
          else
            tar czf "../$BINARY_NAME-${{ matrix.platform.asset-name }}.tar.gz" *
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }}-${{ matrix.platform.asset-name }}.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}